### ISSUE TITLE
Form field placeholders are not localized

### ISSUE THREAD

**Issue by PFischbeck** [Fullscreen/bh#113]
I translated all model attributes in `activerecord.attributes.article`. When generating a form for the model, the field labels are localized (to German, in my case), but the field placeholders are not.
The field labels are generated with the rails method `label`, which uses the localization, but the placeholders are set in [bh/lib/bh/core_ext/rails/form/field_helper.rb](https://github.com/Fullscreen/bh/blob/3cdc03f0c1e2191cdec3b47034666b628eadefd0/lib/bh/core_ext/rails/form/field_helper.rb), which doesn't seem to use localization.

I am generating the form with
```ruby
<%= form_for @article, layout: :basic do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :content %>
    <%= f.submit %>
<% end %>
```

The partially localized result looks like this:
![form](https://cloud.githubusercontent.com/assets/2820802/5602502/dbf3ea70-9351-11e4-98a3-06110c2b0a95.png)

**Comment by claudiofullscreen** [comment]
This is a bug. I will fix it :grimacing:

**Comment by claudiofullscreen** [comment]
@PFischbeck Update to 1.3.0 and try again. Should be fixed.

**Comment by jeroenvisser101** [comment]
Thanks!
