### ISSUE TITLE
navbar adding 'navbar-brand' class to horizontal list

### ISSUE THREAD

**Issue by zenry** [Fullscreen/bh#118]
When using the following ERB template (taken from the docs) with bh (1.3.1) in Rails (4.2.0)

```erb
<%= navbar do %>
    <%= vertical do %>
        <%= link_to 'Home', root_path %>
    <% end %>
    <%= horizontal do %>
        <%= nav class: 'navbar-right' do %>
            <%= link_to 'Profile', root_path %>
            <%= link_to 'Settings', users_path %>
        <% end %>
    <% end %>
<% end %>
```

I end up with

```html
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    
    <div class="navbar-header"><button class="navbar-toggle" data-target="#navbar-collapse-8310700815" data-toggle="collapse" type="button"><span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span></button>

    <a class="navbar-brand" href="/">Home</a>
</div>    <div class="collapse navbar-collapse" id="navbar-collapse-8310700815">
    <ul class="navbar-right nav navbar-nav">
        <li><a class="navbar-brand" href="/">Profile</a></li> <!-- extra navbar-brand class -->
        <li><a class="navbar-brand" href="/admin/users">Settings</a></li> <!-- extra navbar-brand class -->
</ul></div>
  </div>
</nav>
```

I will look into this issue and make a PR if needed

**Comment by jeroenvisser101** [comment]
Indeed seems to be an issue!

**Comment by claudiofullscreen** [comment]
Hello @zenry (and sorry for the delay).

The reason why I add `navbar-brand` is because, in the [Bootstrap navbar documentation](http://getbootstrap.com/components/#navbar), whenever there is an element with `class="navbar-header"`, then the links inside always have the `class="navbar-brand"`.

So, I thought that to be consistent with Bootstrap CSS, you would only have links with the `navbar-brand` class inside the navbar header.

That is indeed the case in all my personal projects where I use Bh.

Could you show me an example that requires an item with `class="navbar-header"` which includes a link **without** the `navbar-brand` class? I could proceed from there…

Thanks!

**Comment by jeroenvisser101** [comment]
@claudiofullscreen If you take a look at the menu on getbootstrap.com itself, they only have `navbar-brand` on their *name*, not all of their links.

**Comment by jeroenvisser101** [comment]
Also note that the other `li > a` items are not contained inside of `navbar-header`.

**Comment by claudiofullscreen** [comment]
>  If you take a look at the menu on getbootstrap.com itself, they only have `navbar-brand` on their name, not all of their links.

@jeroenvisser101 Oooook now I understand. I misread and I thought you were talking about the link inside the `<div class="navbar-header">` element, and that link has the `class="navbar-brand"` applied.

You are saying that the links **inside `horizontal`** should not have the `navbar-brand` class applied, but they do.

Well… I just tried again with a brand new Rails 4.2 app and the latest Bh gem and I actually don't see the `navbar-brand` class inside the `horizontal` links.

Can you [download my test app](https://www.dropbox.com/s/z9up3tl5ypbaoan/test-navbar-brand.zip?dl=1) and tell me if that matches your expectations?

This is the code that I use:

```rhtml
  <%= navbar do %>
    <%= vertical do %>
      <%= link_to 'Home', root_path %>
    <% end %>
    <%= horizontal do %>
      <%= nav class: 'navbar-right' do %>
        <%= link_to 'Profile', root_path %>
        <%= link_to 'Settings', '/#settings' %>
      <% end %>
    <% end %>
  <% end %>
```

and this is the resulting HTML that I see:

```html
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" ...>...</button>
      <a class="navbar-brand" href="/">Home</a>
    </div>    

    <div class="collapse navbar-collapse" id="navbar-collapse-3956354114">
      <ul class="navbar-right nav navbar-nav">
        <li class="active"><a href="/">Profile</a></li>
        <li><a href="/#settings">Settings</a></li>
      </ul>
    </div>
  </div>
</nav>
```

**Comment by claudiofullscreen** [comment]
If you still experience the bug, I will reopen the issue.
