### ISSUE TITLE
link_to produces a link with no link text if the name passed to the helper is nil

### ISSUE THREAD

**Issue by mgoggin** [Fullscreen/bh#120]
The expected functionality is that the following:

```ruby
link_to nil, root_url
```

...will produce

```html
<a href="http://www.example.com">http://www.example.com</a>
```

But in reality, bh's `link_to` helper produces the following:

```html
<a href="http://www.example.com"></a>
```

The bh `link_to` helper should maintain parity with the Rails helper that it overrides where possible.

**Comment by claudiofullscreen** [comment]
thanks! I'll look into this!

**Comment by claudiofullscreen** [comment]
@mgoggin Are you sure that `link_to nil, root_url` is supposed to produce that output in Rails? 
I tried in a normal Rails view, and I got the output with nothing between the `<a>` tags.

Maybe what you intended to write is `link_to root_url` instead?

**Comment by mgoggin** [comment]
I have tested this on a newly generated Rails 4.2 app.

**index.html.erb**
```html
<%= link_to nil, root_url %>
<%= link_to root_url %>
```

This is what is produced:
```html
<a href="http://localhost:4000/">http://localhost:4000/</a>
<a href="http://localhost:4000/">http://localhost:4000/</a>
```

When including bh in the Gemfile, this is what is produced:
```html
<a href="http://localhost:4000/"></a>
<a href="http://localhost:4000/">http://localhost:4000/</a>
```

**Comment by claudiofullscreen** [comment]
@mgoggin Thanks for the clarification! You found a bug :sweat: my bad!

I fixed it and I'm about to release 1.3.2 with the bug fixed.

Before I do that… do you mind referencing the `fix-link-to-without-caption` branch of `bh` in your project, and then try again to check if I've actually 100% fixed the bug?

Simply, in your Gemfile, replace

```ruby
gem 'bh'
```
with

```ruby
gem 'bh', github: 'Fullscreen/bh', branch: 'fix-link-to-without-caption'
```

and tell me if it's okay! Thanks

**Comment by mgoggin** [comment]
I can confirm that the bug is fixed on the `fix-link-to-without-caption` branch.

**Comment by claudiofullscreen** [comment]
Perfect! Now update your gem to `1.3.2` and you're all set!

Thanks again for your feedback.
