### ISSUE TITLE
Broken markup for fields with errors

### ISSUE THREAD

**Issue by atipugin** [Fullscreen/bh#122]
Form with layout: horizontal generates wrong markup. For example:

![screen shot 2015-03-11 at 16 39 09](https://cloud.githubusercontent.com/assets/281812/6597458/e7a55e9e-c80d-11e4-9450-2e38471a5bb9.png)

With following markup:

![screen shot 2015-03-11 at 16 51 28](https://cloud.githubusercontent.com/assets/281812/6597604/e8936958-c80e-11e4-9387-a79314a1c9cf.png)

We definitely can override `field_error_proc` option, but it would be nice it handle out of the box.

**Comment by claudiofullscreen** [comment]
Hello @atipugin – so can I help you, can you paste here your ERB code and the resulting HTML that correspond to the screenshot above? Thanks

**Comment by atipugin** [comment]
Sure. Markup is pretty straightforward (i use Slim):
```slim
= panel title: t('.title') do
  .panel-body
    = form_for @user, url: user_registration_path, layout: :basic do |f|
      = f.email_field :email
      = f.password_field :password
      = f.submit t('.submit')
```

Resulting HTML:
```html
<div class="form-group has-error has-feedback">
  <div class="field_with_errors">
    <label class="control-label" for="user_email">Эл. почта</label>
  </div>
  <div class="field_with_errors">
    <input placeholder="Эл. почта" class="form-control" type="email" value="" name="user[email]" id="user_email">
  </div>
  <span class="form-control-feedback glyphicon glyphicon-remove"></span>
  <span class="help-block text-left">не может быть пустой</span>
</div>
```

**Comment by atipugin** [comment]
Sorry, i meant "basic" layout, not "horizontal" :)

**Comment by claudiofullscreen** [comment]
@atipugin You are right :sweat:, I was able to reproduce the :beetle: 

I noticed that, in my code, if I add `use_label: false` to your field then (apart from hiding the label), it will position the red "X" in the right place. 

I know that's not a fix (and I will look into that now), but give it a try and tell me if that works for you too.

![with_label](https://cloud.githubusercontent.com/assets/7408595/6598343/54ed23f4-c7c0-11e4-88ff-443fa94ad499.png)

![without_label](https://cloud.githubusercontent.com/assets/7408595/6598345/58031ec2-c7c0-11e4-8757-1713e8b50e2b.png)

**Comment by claudiofullscreen** [comment]
Also… could you confirm that you only have the problem with the basic layout? Looks like horizontal and inline work fine:

![horizontal](https://cloud.githubusercontent.com/assets/7408595/6598379/930e289a-c7c0-11e4-84ce-7d3e8daa0cf2.png)
![inline](https://cloud.githubusercontent.com/assets/7408595/6598380/932ecc58-c7c0-11e4-8696-38ddfb7e2b69.png)

**Comment by atipugin** [comment]
Yep, horizontal layout works just fine. Hiding label is not an option in my case, so i'll stick with custom `field_error_proc` for now :(

**Comment by claudiofullscreen** [comment]
@atipugin 

I think I fixed the bug and I'm about to release 1.3.3 with the bug fixed.

Before I do that… do you mind temporarily referencing the `fix-error-icon-in-basic-form` branch of bh in your project, and then try again to check if I've actually 100% fixed the bug?

Simply, in your Gemfile, replace

```ruby
gem 'bh'
```

with

```ruby
gem 'bh', github: 'Fullscreen/bh', branch: 'fix-error-icon-in-basic-form'
```

and tell me if it's okay! Thanks

**Comment by atipugin** [comment]
Yes, now it works! Looking for the release :)

**Comment by claudiofullscreen** [comment]
@atipugin You can now update to 1.3.3! :tada:
