### ISSUE TITLE
Not compatible with Rails 3.0

### ISSUE THREAD

**Issue by gamov** [Fullscreen/bh#125]
When I try to run your gem with Rails 3.0.20, I get the following errors:

```ruby
.rvm/gems/ruby-1.9.3-p545@ector/gems/bh-1.0.0/lib/bh/helpers/base_helper.rb:7:in `<module:BaseHelper>': uninitialized constant ActionView::Helpers::OutputSafetyHelper (NameError)
.rvm/gems/ruby-1.9.3-p545@ector/gems/bh-1.3.3/lib/bh/core_ext/rails/base_helper.rb:9:in `<module:BaseHelper>': uninitialized constant ActionView::Helpers::OutputSafetyHelper (NameError)
.rvm/gems/ruby-1.9.3-p545@ector/gems/bh-1.2.0/lib/bh/core_ext/rails/base_helper.rb:9:in `<module:BaseHelper>': uninitialized constant ActionView::Helpers::OutputSafetyHelper (NameError)
.rvm/gems/ruby-1.9.3-p545@ector/gems/bh-1.1.1/lib/bh/helpers/base_helper.rb:7:in `<module:BaseHelper>': uninitialized constant ActionView::Helpers::OutputSafetyHelper (NameError)
```
OutputSafetyHelper only appeared on Rails 3.1 but it seems ok to back port it:
http://apidock.com/rails/v3.1.0/ActionView/Helpers/OutputSafetyHelper/safe_join
Would you like to import it in the gem?

**Comment by claudiofullscreen** [comment]
Hello @gamov! I didn't make plan to support Rails 3 since [it's not maintained anymore](http://guides.rubyonrails.org/maintenance_policy.html).

**Comment by gamov** [comment]
I see, the read me says *Bh is compatible with Rails 3* so I thought 3.0.20 was included.

**Comment by claudiofullscreen** [comment]
Oooooh that's fair! Then I'll keep this ticket open and either fix it or change the README

**Comment by gamov** [comment]
😃
it's just safe_join that is needed I think.
By the way, I love this gem. So much needed!

**Comment by claudiofullscreen** [comment]
Hello again. You’re right, Rails 3.0 is not supported. 

I will change the Gemfile and the README to indicate that Rails 3.2 is required at least.

Since Rails 3.2.0 was released more than 3 years ago, I think that's old enough to give people a chance to update and still use bh. Even though… upgrading to Rails 4 (and upcoming Rails 5) is still highly encouraged :wink:
