### ISSUE TITLE
Validations when using fields_for not displaying correctly

### ISSUE THREAD

**Issue by KMontag42** [Fullscreen/bh#131]
Hey!

Another `fields_for` related issue that I've come across.

Here is a screenshot of the form that I am working on (standard devise goodness)
![image](https://cloud.githubusercontent.com/assets/1686738/7684629/8578ae38-fd55-11e4-8d1d-f96fb6f9afa3.png)

As you can see the validations are working great for the first-level form fields.

Here is the form's view itself:
```erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), layout: :basic) do |f| %>

  <%= f.text_field :first_name, autofocus: true %>

  <%= f.text_field :last_name %>

  <%= f.fields_for :foo, fieldset: false do |foo| %>
    <%= foo.text_field :name, label: 'Company' %>
  <% end %>

  <%= f.email_field :email %>

  <%= f.password_field :password, help: 'Minimum 8 characters' %>

  <%= f.password_field :password_confirmation, autocomplete: "off" %>

  <%= f.submit "Sign up", class: 'btn-lg btn-block' %>

<% end %>
```

However for the `foo` model, I have this validator:
```ruby
validates_uniqueness_of :name, case_sensitive: false
```

When I run a debugger and check the errors on the `resource` I can see the proper error listed:
(added \n for readability)
```ruby
#<ActiveModel::Errors:0x000001143b0528 
@base=#<User id: nil, email: "kmontag@foobar.com", 
encrypted_password: "$2a$10$AiSLZb7QcPt9cNbCeubVmeyO/32le4NbTEoF0vEGsL/...",
reset_password_token: nil, 
reset_password_sent_at: nil, 
remember_created_at: nil, 
sign_in_count: 0, 
current_sign_in_at: nil, 
last_sign_in_at: nil, 
current_sign_in_ip: nil,
last_sign_in_ip: nil, 
created_at: nil, 
updated_at: nil, 
first_name: "", 
last_name: "Montag", 
publisher_id: nil, 
invitation_token: nil, 
invitation_created_at: nil, 
invitation_sent_at: nil, 
invitation_accepted_at: nil,
invitation_limit: nil,
invited_by_id: nil,
invited_by_type: nil, 
invitations_count: 0>, 
@messages={
:"foo.name"=>["has already been taken"], 
:first_name=>["can't be blank"], 
:email=>["has already been taken"]}
>
```

The `:foo.name` error is in `resource.errors` correctly, however it isn't showing up on the form at all.

The model relations in question are:
```
User
belongs_to :foo
```
```
foo
has_many :users
```

And the `resource` in the form is a `User`

Any ideas? Am I missing something?

<3

**Comment by wengs** [comment]
Hey @KMontag42,

First of all, I assumed you created your own registration controller similar to the following:
```ruby
class RegistrationsController < Devise::RegistrationsController
  def new
    build_resource({})
    self.resource.foo = Foo.new
	respond_with self.resource
  end

  private

  def sign_up_params
  	allow = [:email, :password, :password_confirmation, [foo_attributes: [:name]]]
  	params.require(resource_name).permit(allow)
  end
end 
```
Then, if you look at the [error section in bh documentation](http://fullscreen.github.io/bh/#form-errors), you will see "Fields inside bootstrapped forms submitted with invalid values are automatically highlighted," which makes me think bh does not know how to deal with errors occurs in fields_for. You need to tell bh that fields_for will also have error messages by using the customize ```:errors``` option, so you want to do something like the following: 
```ruby
<%= f.fields_for :foo, fieldset: false, errors: {icons: true, messages: true } do |foo_form| %>
      <%= foo_form.text_field :name, label: 'Company' %>
      <% if resource.foo.errors.any? %>
        <ul class="errors">
          <% resource.foo.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
```
Unfortunately, bh only highlights the text_field :name even though the messages option is specified as true. However, you don't need a form_for or devise to display error messages. You can display the error messages by iterating all error messages of foo attributes.

I also suggest you to specify ```accepts_nested_attributes_for :foo``` in your  ```User``` model to ensure the Foo is saved through User.

**Comment by KMontag42** [comment]
![](https://i.imgur.com/872FDBm.gif)

This is exactly what I needed! Thank you so much for the information and very detailed response!!
