### ISSUE TITLE
Errors highlighting

### ISSUE THREAD

**Issue by ahmed-isam** [Fullscreen/bh#134]
I am having an issue with errors highlighting, I've tried to do extend to field with errors in the CSS but didn't work. I hope someone's got a solution for that.

**Comment by claudiofullscreen** [comment]
@ahmed-isam Thanks for stopping by!

Can you paste an example of the code you are using and what you are trying to achieve? Thanks!

**Comment by ahmed-isam** [comment]
This is the code

			<%= form_for :legal_entity, layout: :horizontal, :url => {:action => "create"} do |f| %>
				<%= f.text_field :entity_name, label: "Entity Name" %>
				<%= f.text_field :address %>
				<%= f.text_field :cc_emails, label: "CC Emails", placeholder: "Comma Seperated Email Addresses" %>
				<%= f.text_field :accounting_contact_name, label: "Accounting Contact Name" %>
				<%= f.text_field :accounting_contact_phone, label: "Accounting Contact Phone" %>
				<%= f.text_field :compliance_contact_name, label: "Compliance Contact Name" %>
				<%= f.text_field :compliance_contact_phone, label: "Compliance Contact Phone" %>
				<%= f.check_box :verified %>
				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-9"> 
						<input class="btn btn-success" name="commit" type="submit" value="Create"/>
						<%= link_to("Cancel", {:action => "index"}, :class => "btn btn-danger") %>
					</div>
				</div>
			<% end %>

I just want it to show the input field and the label in red, and to display the error below the filed, just like the documentation. I am using validate_presence_of helper in the model and showing errors using the object.error.full_messages

**Comment by claudiofullscreen** [comment]
@ahmed-isam When you use Bh, a `form_for` with horizontal layout (like the one you are using) automatically displays error messages around the fields with errors.

If you want to override this behavior and deal with errors with your own HTML/CSS, you can add the `, errors: {messages: false}` option to `form_for`. In your code above, this would be:

```rhtml
<%= form_for :legal_entity, layout: :horizontal, errors: {messages: false}, :url => {:action => "create"} do |f| %>
...
<% end %>
```

---

If this doesn't work for you please let me know, in the snippet of code you pasted, *which* field is having a validation error and does not show an error message. Thanks!

**Comment by ahmed-isam** [comment]
It's only the name (:entity_name), I am just learning how to use the bh gem. I have tried without using anything, but it didn't highlight. Even with setting messages to true. Still get no highlighting.

Still no luck

**Comment by claudiofullscreen** [comment]
@ahmed-isam If your full repository is available online, I can take a look.

**Comment by ahmed-isam** [comment]
I will add it to Git. Sure. Thank you for your time

**Comment by ahmed-isam** [comment]
Oh sorry, I can't share the code, I am working on something that will become an internal application. Is there a way to send it directly to you?

**Comment by ahmed-isam** [comment]
I have also looked at the generated DOM, it only generate the field-with-errors classes, not the has-error classes

**Comment by ahmed-isam** [comment]
Any thoughts?
