### ISSUE TITLE
Possible vulnerability in BH 1.3.3?

### ISSUE THREAD

**Issue by emilebosch** [Fullscreen/bh#138]
Hi! I've been getting unsanitized data back from the `gem bh`. I've tried to isolate the issue and it seems to be the case with at least version 1.3.3.

Scenario: 

1. User name contains `<script>alert("yolo")</script>` in the database.

Whereas without BH yields good escaped HTML, this version of BH doesn't seem to do this. Can anyone confirm this if the case. If so we need to open a SECURITY issue in the rails security group and yank this version.

```
= link_to User.first.name, "ok"
```

We've been using:

```
    bh (1.3.3)
      actionpack
      activesupport
```
Can someone check if this is the case?

**Comment by emilebosch** [comment]
@claudiob

**Comment by claudiofullscreen** [comment]
I was able to reproduce your steps. Looking into it. Thanks for the feedback.

**Comment by emilebosch** [comment]
Ok cool thanks for the response, do you want to write me a CVE + announcement. I think i'd be appropriate. If we file A CVE we people with brakeman, or bundler-audit will be warned. Let me know !
and contact me on emilebosch@me.com for more details :)

**Comment by claudiofullscreen** [comment]
Hello @emilebosch – before I merge, push and release, can you do a last check that my pull request fixes the bug?

Temporarily point your Gemfile to the following branch and confirm that the bug is fixed:

`gem 'bh', github: 'claudiofullscreen/bh', branch: 'fix-security'`

**Comment by emilebosch** [comment]
hey thanks for the quick response. However im not able tot properly check now. but i'd rather want you to not override the default rails helpers. instead of fixing it. it leads to unexpected behavior. i'd recomment you yank your versions, put out an CVE, and make your custom  helpers.

**Comment by claudiob** [comment]
Are you talking about #136 ?

**Comment by claudiofullscreen** [comment]
1.3.4 includes the patch above.

**Comment by emilebosch** [comment]
Good for fixing it although, without trying to sound like an unappreciative and i do like your work, i think you should take more appropriate actions such as:

- Yank your gem versions that are vulnerable, and push a new one.
- Put a notice on your `Readme.md`
- Write out a CVE so that tools like brakeman and bundler audit warn on your insecure gem version

The reason is that now every site who uses your gem and  not the latest version has a huge hole in their application.

Let's say someone registers a user with the name `<script>document.cookie</script>` and then use `link_to current.user.name, current_user` in the profile. Then their site is vulnerable for XSS and Cookie theft. 

Can you please do it, or else i'll set up a CVE, for the mean time, my fork has the helpers removed. Again   thanks and if you have any questions. Contact me.

**Comment by claudiofullscreen** [comment]
@emilebosch Yes, thanks for all your feedback. I'm going to do that!

**Comment by claudiofullscreen** [comment]
@emilebosch I have never dealt with a security issue before so I need your help.

Since the `safe_join` was introduced in 1.2.0, are you suggesting I should yank all the versions from 1.2.0 to 1.3.3?

Also… is there a template to file a CVE?
